import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseCustomCardFragment, parseCustomRules } from "../src/shared/custom-rules-parser.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const jsonDir = join(root, "json");
const outFile = join(root, "src", "shared", "generated", "custom-json.generated.ts");

const PLATFORM_PRESET_ID = "all-cards-classic-deck";

function readJsonText(name: string): string {
  return readFileSync(join(jsonDir, name), "utf8");
}

const fragments: Record<string, unknown> = {};
const fragmentsDir = join(jsonDir, "cards");
for (const file of readdirSync(fragmentsDir)) {
  if (!file.endsWith(".json")) continue;
  const id = file.replace(/\.json$/, "");
  fragments[id] = parseCustomCardFragment(readFileSync(join(fragmentsDir, file), "utf8"));
}

const platformSource = JSON.parse(readJsonText(`${PLATFORM_PRESET_ID}.json`)) as Record<string, unknown> & {
  cards?: Record<string, unknown>;
};
platformSource.cards = { ...(platformSource.cards ?? {}), ...fragments };
const platformPreset = parseCustomRules(platformSource);

const content = `// This file is generated by scripts/sync-custom-json.ts. Do not edit by hand.
import { deepFreeze } from "../stable-json.js";
import type { ResolvedCustomRules } from "../custom-rules-types.js";

export const PLATFORM_PRESET_ID = ${JSON.stringify(PLATFORM_PRESET_ID)};

export const PLATFORM_PRESET: ResolvedCustomRules = deepFreeze(${JSON.stringify(platformPreset, null, 2)});
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, content, "utf8");
console.log(`custom-json synced: preset=${platformPreset.name} hash=${platformPreset.hash.slice(0, 12)} cards=${Object.keys(platformPreset.cards).length}`);
